import { getPages } from '@/sanity/sanity-utils'
import '../globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'My website',
  description: 'Generated by next-sanity',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const pages = await getPages();
  
  return (
    <html lang="en">
      <body className="max-w-full mx-auto bg-[url('https://cdn.discordapp.com/attachments/692106586147127296/1133918537497444525/IMG_3046.jpg')]">

        <header className="h-32 bg-white mb-0 flex items-center justify-between">
          <Link href="/"
            className="ml-32 bg-gradient-to-r from-blue-400 via-blue-500 to-blue-600
            bg-clip-text text-transparent text-3xl font-bold">Home
          </Link>
          <div className="mr-32 flex items-center gap-5 text-3xl text-gray-600">
            {pages.map((page) => (
              <Link key={page._id} href={`/${page.slug}`} className="hover:underline">
                {page.title}
              </Link>
            ))}
          </div>
        </header>
        <main className="max-w-6xl mx-auto">{children}</main>
        
        
      </body>
    </html>
  )
}
